<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Pre-aggregated daily snapshot per branch per day.
     * Generated by DailySummary::generate($branchId, $date) — called
     * when a cash session closes or via the daily artisan command.
     *
     * net_income = gross_sales - total_refunds - total_expenses
     * over_short = counted_cash - expected_cash
     *
     * is_finalized = true means the manager has verified and locked it.
     * Locked records are skipped on auto-regeneration (use force=true to override).
     */
    public function up(): void
    {
        Schema::create('daily_summaries', function (Blueprint $table) {
            $table->id();
            $table->date('summary_date');
            $table->foreignId('branch_id')->constrained('branches')->cascadeOnDelete();

            // Sales
            $table->integer('total_transactions')->default(0);
            $table->decimal('gross_sales', 12, 2)->default(0.00);
            $table->decimal('total_refunds', 12, 2)->default(0.00);

            // Payment breakdown
            $table->decimal('cash_sales', 12, 2)->default(0.00);
            $table->decimal('gcash_sales', 12, 2)->default(0.00);
            $table->decimal('card_sales', 12, 2)->default(0.00);
            $table->decimal('other_sales', 12, 2)->default(0.00);

            // Cash drawer
            $table->decimal('opening_cash', 10, 2)->default(0.00);
            $table->decimal('expected_cash', 10, 2)->default(0.00);
            $table->decimal('counted_cash', 10, 2)->nullable();
            $table->decimal('over_short', 10, 2)->default(0.00);

            // Expenses
            $table->decimal('total_expenses', 12, 2)->default(0.00);
            $table->json('expenses_by_category')->nullable(); // {"Utilities":500,"Supplies":120}

            // Net result
            $table->decimal('net_income', 12, 2)->default(0.00);

            // Inventory snapshot
            $table->integer('items_sold')->default(0);
            $table->integer('low_stock_count')->default(0);

            // Finalization
            $table->boolean('is_finalized')->default(false);
            $table->foreignId('finalized_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('finalized_at')->nullable();
            $table->text('notes')->nullable();

            $table->timestamps();

            $table->unique(['summary_date', 'branch_id']);
            $table->index('summary_date');
            $table->index('branch_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('daily_summaries');
    }
};
